// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBhS27Z9nbPl5A1T9NCCAiMp4Xbh9kCk',
    appId: '1:588610136214:web:82d845f5f33b57d304bab7',
    messagingSenderId: '588610136214',
    projectId: 'quick-learner-a6968',
    authDomain: 'quick-learner-a6968.firebaseapp.com',
    storageBucket: 'quick-learner-a6968.firebasestorage.app',
    measurementId: 'G-J17MSZR3KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8I7_jR365xbw_gkbLCzCT3LK9BZhae0',
    appId: '1:588610136214:android:14fefe6bf10ac2ae04bab7',
    messagingSenderId: '588610136214',
    projectId: 'quick-learner-a6968',
    storageBucket: 'quick-learner-a6968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEieepxM6WpNHDsgmOpYRHQ70zuX7E2yQ',
    appId: '1:588610136214:ios:c03f05529f649f4104bab7',
    messagingSenderId: '588610136214',
    projectId: 'quick-learner-a6968',
    storageBucket: 'quick-learner-a6968.firebasestorage.app',
    iosBundleId: 'com.example.quickLearner',
  );
}
